#Phase 1 Project

In [3]:
#LOADING PANDAS
import pandas as pd

In [4]:
#loading Aviation Data

file_path = 'C:\\Users\\KimauC\\OneDrive - SAFAL GROUP\\Desktop\\DATA SCIENCE\\\Project P1\\AviationData.csv'
aviation_data = pd.read_csv(file_path, encoding='ISO-8859-1')

c:\Users\KimauC\AppData\Local\anaconda3\envs\learn-env\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (6,7,28) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
#Checking the first 5 Rows
aviation_data.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.9222,-81.8781,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [6]:
#checking info in the Aviation data
aviation_data.info

<bound method DataFrame.info of              Event.Id Investigation.Type Accident.Number  Event.Date  \
0      20001218X45444           Accident      SEA87LA080  1948-10-24
1      20001218X45447           Accident      LAX94LA336  1962-07-19
2      20061025X01555           Accident      NYC07LA005  1974-08-30
3      20001218X45448           Accident      LAX96LA321  1977-06-19
4      20041105X01764           Accident      CHI79FA064  1979-08-02
...               ...                ...             ...         ...
88884  20221227106491           Accident      ERA23LA093  2022-12-26
88885  20221227106494           Accident      ERA23LA095  2022-12-26
88886  20221227106497           Accident      WPR23LA075  2022-12-26
88887  20221227106498           Accident      WPR23LA076  2022-12-26
88888  20221230106513           Accident      ERA23LA097  2022-12-29

              Location        Country Latitude Longitude Airport.Code  \
0      MOOSE CREEK, ID  United States      NaN       NaN          NaN
1       BRIDGEPORT, CA  United States      NaN       NaN          NaN
2        Saltville, VA  United States  36.9222  -81.8781          NaN
3           EUREKA, CA  United States      NaN       NaN          NaN
4           Canton, OH  United States      NaN       NaN          NaN
...                ...            ...      ...       ...          ...
88884    Annapolis, MD  United States      NaN       NaN          NaN
88885      Hampton, NH  United States      NaN       NaN          NaN
88886       Payson, AZ  United States  341525N  1112021W          PAN
88887       Morgan, UT  United States      NaN       NaN          NaN
88888       Athens, GA  United States      NaN       NaN          NaN

      Airport.Name  ... Purpose.of.flight         Air.carrier  \
0              NaN  ...          Personal                 NaN
1              NaN  ...          Personal                 NaN
2              NaN  ...          Personal                 NaN
3              NaN  ...          Personal                 NaN
4              NaN  ...          Personal                 NaN
...            ...  ...               ...                 ...
88884          NaN  ...          Personal                 NaN
88885          NaN  ...               NaN                 NaN
88886       PAYSON  ...          Personal                 NaN
88887          NaN  ...          Personal  MC CESSNA 210N LLC
88888          NaN  ...          Personal                 NaN

      Total.Fatal.Injuries Total.Serious.Injuries Total.Minor.Injuries  \
0                      2.0                    0.0                  0.0
1                      4.0                    0.0                  0.0
2                      3.0                    NaN                  NaN
3                      2.0                    0.0                  0.0
4                      1.0                    2.0                  NaN
...                    ...                    ...                  ...
88884                  0.0                    1.0                  0.0
88885                  0.0                    0.0                  0.0
88886                  0.0                    0.0                  0.0
88887                  0.0                    0.0                  0.0
88888                  0.0                    1.0                  0.0

      Total.Uninjured Weather.Condition  Broad.phase.of.flight  \
0                 0.0               UNK                 Cruise
1                 0.0               UNK                Unknown
2                 NaN               IMC                 Cruise
3                 0.0               IMC                 Cruise
4                 0.0               VMC               Approach
...               ...               ...                    ...
88884             0.0               NaN                    NaN
88885             0.0               NaN                    NaN
88886             1.0               VMC                    NaN
88887             0.0               NaN                    NaN
88888             1.0               NaN                    NaN

        Report.Status Publication.Date
0      Probable Cause              NaN
1      Probable Cause       19-09-1996
2      Probable Cause       26-02-2007
3      Probable Cause       12-09-2000
4      Probable Cause       16-04-1980
...               ...              ...
88884             NaN       29-12-2022
88885             NaN              NaN
88886             NaN       27-12-2022
88887             NaN              NaN
88888             NaN       30-12-2022

[88889 rows x 31 columns]>

In [7]:
# Columns in the aviation_data
aviation_data.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date'],
      dtype='object')

In [8]:
#Calling NaN_values

NaN_values = aviation_data.isnull().sum()
NaN_values

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38640
Airport.Name              36099
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1317
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7077
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6381
Publication.Date          13771
dtype: int64

In [9]:
#Filling missing numeric data with column-wise median values.

numeric_columns = aviation_data.select_dtypes(include=['float64', 'int64']).columns
for col in numeric_columns:
    aviation_data[col].fillna(aviation_data[col].median(), inplace=True)

In [10]:
#Filling missing categorical data with most frequent values (mode).

categorical_columns = aviation_data.select_dtypes(include=['object']).columns
for col in categorical_columns:
    aviation_data[col].fillna(aviation_data[col].mode()[0], inplace=True)

In [11]:
#Dropping Null Values

cleaned_data = aviation_data.dropna()

cleaned_data.head().sum().isnull()

Event.Id                  False
Investigation.Type        False
Accident.Number           False
Event.Date                False
Location                  False
Country                   False
Airport.Code              False
Airport.Name              False
Injury.Severity           False
Aircraft.damage           False
Aircraft.Category         False
Registration.Number       False
Make                      False
Model                     False
Amateur.Built             False
Number.of.Engines         False
Engine.Type               False
FAR.Description           False
Schedule                  False
Purpose.of.flight         False
Air.carrier               False
Total.Fatal.Injuries      False
Total.Serious.Injuries    False
Total.Minor.Injuries      False
Total.Uninjured           False
Weather.Condition         False
Broad.phase.of.flight     False
Report.Status             False
Publication.Date          False
dtype: bool

In [12]:
aviation_data.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,332739N,0112457W,NONE,Private,...,Personal,Pilot,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,25-09-2020
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,332739N,0112457W,NONE,Private,...,Personal,Pilot,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.9222,-81.8781,NONE,Private,...,Personal,Pilot,3.0,0.0,0.0,1.0,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,332739N,0112457W,NONE,Private,...,Personal,Pilot,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,332739N,0112457W,NONE,Private,...,Personal,Pilot,1.0,2.0,0.0,0.0,VMC,Approach,Probable Cause,16-04-1980

In [13]:
#checking new data after cleaning
cleaned_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88889 non-null  object
 5   Country                 88889 non-null  object
 6   Latitude                88889 non-null  object
 7   Longitude               88889 non-null  object
 8   Airport.Code            88889 non-null  object
 9   Airport.Name            88889 non-null  object
 10  Injury.Severity         88889 non-null  object
 11  Aircraft.damage         88889 non-null  object
 12  Aircraft.Category       88889 non-null  object
 13  Registration.Number     88889 non-null  object
 14  Make                    88889 non-null  object
 15  Model                   88889 non-null  object
 16  Amateur.Built           88889 non-null  object
 17  Number.of.Engines       88889 non-null  float64
 18  Engine.Type             88889 non-null  object
 19  FAR.Description         88889 non-null  object
 20  Schedule                88889 non-null  object
 21  Purpose.of.flight       88889 non-null  object
 22  Air.carrier             88889 non-null  object
 23  Total.Fatal.Injuries    88889 non-null  float64
 24  Total.Serious.Injuries  88889 non-null  float64
 25  Total.Minor.Injuries    88889 non-null  float64
 26  Total.Uninjured         88889 non-null  float64
 27  Weather.Condition       88889 non-null  object
 28  Broad.phase.of.flight   88889 non-null  object
 29  Report.Status           88889 non-null  object
 30  Publication.Date        88889 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.7+ MB

In [28]:
# Standardizing the Injury.Severity column by replacing any entry that starts with "Fatal" to just "Fatal"

aviation_data['Injury.Severity'] = aviation_data['Injury.Severity'].apply(lambda x: "Fatal" if "Fatal" in str(x) else x)

aviation_data.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,332739N,0112457W,NONE,Private,...,Personal,Pilot,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,25-09-2020
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,332739N,0112457W,NONE,Private,...,Personal,Pilot,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.9222,-81.8781,NONE,Private,...,Personal,Pilot,3.0,0.0,0.0,1.0,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,332739N,0112457W,NONE,Private,...,Personal,Pilot,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,332739N,0112457W,NONE,Private,...,Personal,Pilot,1.0,2.0,0.0,0.0,VMC,Approach,Probable Cause,16-04-1980

In [15]:
#Saving Cleaned File
output_file_path = 'cleaned_aviation_data.csv'

# Saving the cleaned data to a CSV file without the index
cleaned_data.to_csv(output_file_path, index=False)

print(f"Cleaned data has been saved to {output_file_path}")

Cleaned data has been saved to cleaned_aviation_data.csv

In [16]:
#Categorizing Data in New column Error.type to determine if the error is Pilot related or Mechanical 

df = pd.read_csv('cleaned_aviation_data.csv')

# Replacing 'Report.Status' with the actual name of the column if different
df['Error.type'] = df['Report.Status'].apply(lambda x: 'Pilot error' if 'pilot' in str(x).lower() else 'Mechanical error')

df.to_csv('updated_aviation_data.csv', index=False)

In [17]:
df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,Error.type
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,332739N,0112457W,NONE,Private,...,Pilot,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,25-09-2020,Mechanical error
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,332739N,0112457W,NONE,Private,...,Pilot,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996,Mechanical error
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922222999999995,-81.878056,NONE,Private,...,Pilot,3.0,0.0,0.0,1.0,IMC,Cruise,Probable Cause,26-02-2007,Mechanical error
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,332739N,0112457W,NONE,Private,...,Pilot,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000,Mechanical error
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,332739N,0112457W,NONE,Private,...,Pilot,1.0,2.0,0.0,0.0,VMC,Approach,Probable Cause,16-04-1980,Mechanical error

In [21]:

# Calculating  the survival rate and creating a new column 'Survival.Rate'
df['Survival.Rate'] = ((df['Total.Serious.Injuries'] + df['Total.Minor.Injuries'] + df['Total.Uninjured']) /
                       (df['Total.Fatal.Injuries'] + df['Total.Serious.Injuries'] + df['Total.Minor.Injuries'] + df['Total.Uninjured'])) * 100
df.to_csv('updated_aviation_data_with_survival_rate.csv', index=False)

In [46]:

# Loading the data from the uploaded file
file_path = 'C:\\Users\\KimauC\\OneDrive - SAFAL GROUP\\Desktop\\DATA SCIENCE\\Project P1\\final_updated_aviation_data_with_survival_rate.csv'
aviation_data = pd.read_csv(file_path)

# Standardizing the Injury.Severity column by replacing any entry that starts with "Fatal" to just "Fatal"
aviation_data['Injury.Severity'] = aviation_data['Injury.Severity'].apply(lambda x: "Fatal" if "Fatal" in str(x) else x)

# Creating a new column 'Fatality' which marks 'Fatal' for Fatal and 'Non-Fatal' for others
aviation_data['Fatality'] = aviation_data['Injury.Severity'].apply(lambda x: "Fatal" if x == "Fatal" else "Non_Fatal")

# Saving the cleaned DataFrame with the new 'Fatality' column to a new CSV file
aviation_data.to_csv('the_final_updated_aviation_data_with_fatality.csv', index=False)

In [43]:
aviation_data.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date', 'Error.type', 'Survival.Rate', 'Fatality'],
      dtype='object')